# Files: Reference Genome, Reference Panel, Sample Sheet
ref: /local/storage/reference_small_tree_finch/small_tree_finch_genome.fna
panel: /local/storage/phased_reference_panel/chrZ.415samps.postrecomb.bcf
csv: /SSD/reg259/finch_genome_imputation/project/samples_NCBI.csv

# Options: local, remote_fs, NCBI
input_type: NCBI

# Genetic Maps Directory
gmap: /local/storage/gmap_files

# List of chromosomes to use
# Note: chromosomes must also be present in the reference genome, reference panel, and genetic maps
chrs: ["chrZ"]