# Files
# Reference Genome
ref: /SSD/reg259/finch_genome_imputation/reference/small_tree_finch_genome.fna
# Reference Panel
panel: /SSD/reg259/finch_genome_imputation/panel/finches_sentieon_concat_SNPs_fil_setGT_PASS_BIALLELIC_ACf.vcf.gz
# Sample Reads
reads_local: False
reads_remote_fs: False
csv: /SSD/reg259/finch_genome_imputation/final_project/samples.csv
# Or NCBI Data
NCBI_data: True
NCBI_Accession: PRJNA392917
# Average Depth Script
script: /SSD/reg259/finch_genome_imputation/scripts/average_depth.py

# Directories
# Genetic Maps
gmap: /SSD/reg259/finch_genome_imputation/gmap_files
# Environments
envs: /SSD/reg259/finch_genome_imputation/envs